language: node_js
node_js:
  - 12
cache: npm
branches:
  only:
    - backup # build master branch only
script:
  - hexo clean
  - hexo generate
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: backup
  local-dir: public